name: CI-CD-Pipeline-to-AWS-ElasticBeansTalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "gthb-flask-app-productions"
  EB_APPLICATION_NAME       : "MyFlaskApp"
  EB_ENVIROMENT_NAME        : "Myflaskapp-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  REGION_NAME               : "us-east-2"

on:
  push:
    branches:
      - main


jobs:
  my_ci_pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone repo
        uses: actions/checkout@v2
        
      - name: Create zip package
        run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
        
      - name: Configure AWS credentials
        uses: aws-action/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-key-id: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region       : ${{ env.REGION_NAME }}
          
      - name: Copy deploy package to S3 bucket
        run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }}  s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
        
      - name: Print message
        run : echo "CI Pipeline finished successfully!"
      
